function st_lidar_cfg = fillVlp16PuckCfg(scan)

[max_elevation, min_elevation, max_azimuth, min_azimuth] = maxMinElevation(scan);

st_lidar_cfg = struct('max_elevation', max_elevation, ...
                                'min_elevation', min_elevation, ...
                                'max_azimuth',  max_azimuth, ...
                                'min_azimuth',   min_azimuth, ...
                                'max_range',      100.0, ...
                                'res_elevation',  2.0, ...
                                'res_azimuth',    0.2, ...
                                'elevation_cells', 0, ...
                                'azimuth_cells',   0);
                       
st_lidar_cfg.azimuth_cells = 1 + (st_lidar_cfg.max_azimuth - st_lidar_cfg.min_azimuth) / st_lidar_cfg.res_azimuth;
st_lidar_cfg.elevation_cells = 1 + (st_lidar_cfg.max_elevation - st_lidar_cfg.min_elevation) / st_lidar_cfg.res_elevation;
end

